### ISSUE TITLE
Line break failure when more than one group of \n\n, when enter or delete at one \n\n position, the other line break will be lost

### ISSUE THREAD

**Issue by rex-0085** [Harbour-Enterprises/SuperDoc#842]
test code as following
`event.superdoc.activeEditor.commands.insertContent(' Leftwich R.W, 1981, “Evidence of the Impact of Mandatory Changes in Accounting Economics Principles on\n\nZmijewskiM.E., Hagerman R.L., 1981, “An Income Strategy Approach to the Positive Theory of Accounting Standard Settings/Choice”, Journal of Accounting and Economics, 129-149\n\nZmijewskiM.E., Hagerman R.L., 1981, “An Income Strategy Approach to the Positive Theory of Accounting Standard Settings/Choice”, Journal of Accounting and Economics, 129-149')`

**Comment by rex-0085** [comment]
`.replace(/\n/g, <br>) is useful`

**Comment by harbournick** [comment]
@rex-0085 this is fixed in 'next' tag now via https://github.com/Harbour-Enterprises/SuperDoc/commit/dd60d91711e63741e2d6ca2ced02251f2a4e0465

Will be in 'latest' shortly

**Comment by rex-0085** [comment]
hi nick. I test version0.16.2. the issue still exist, could you plz have a look.

after loading you need to press "delete" at one linebreak, you can find other linebreaks lose
@harbournick
